[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
storage = { path = "../storage" }
bytes = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
crc32c = "0.6"
anyhow = "1"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
